### ISSUE TITLE
apps missing? f-droid base repository currently has 3134 apps while the SkyDroid-F-Droid only has 519

### ISSUE THREAD

**Issue by k3b** [redsolver/skydroid-fdroid-bridge#1]

**Comment by redsolver** [comment]
Currently, every F-Droid app updated after 2020-07-01 is available. I just changed the code to include every app available on F-Droid. I will let you know when syncing is done.

**Comment by redsolver** [comment]
All 3142 apps from the main repo are now available on SkyDroid. Every app updated after 2019-08-11 is included in the `fdroid-app` collection, older apps can be accessed via a link (for example https://to.skydroid.app/de.stefan_oltmann.kaesekaestchen.fdroid-app or http://to.skydroid.app/com.totsp.bookworm.fdroid-app)
